config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  post "/graphql", to: "graphql#execute"
  mount ShopifyApp::Engine, at: "/"
  root to: "products#index"
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

module Ckeditor
  class Asset < ApplicationRecord
    include Ckeditor::Orm::ActiveRecord::AssetBase
    include Ckeditor::Backend::Paperclip
  end
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

module Ckeditor
  class AttachmentFile < Ckeditor::Asset
    has_attached_file :data,
                      url:  "/ckeditor_assets/attachments/:id/:filename",
                      path: ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

    validates_attachment_presence :data
    validates_attachment_size :data, less_than: 100.megabytes
    do_not_validate_attachment_file_type :data

    def url_thumb
      @url_thumb ||= Ckeditor::Utils.filethumb(filename)
    end
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

module Ckeditor
  class Picture < Ckeditor::Asset
    has_attached_file :data,
                      url:    "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                      path:   ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                      styles: {content: "800>", thumb: "118x100#"}

    validates_attachment_presence :data
    validates_attachment_size :data, less_than: 2.megabytes
    validates_attachment_content_type :data, content_type: /\Aimage/

    def url_content
      url(:content)
    end
  end
end

app/models/shop.rb
# frozen_string_literal: true

class Shop < ApplicationRecord
  include ShopifyApp::SessionStorage

  def api_version
    ShopifyApp.configuration.api_version
  end

  def connect_to_store
    session = ShopifyAPI::Session.new(domain: shopify_domain, token: shopify_token, api_version: api_version)
    session.valid?
    ShopifyAPI::Base.activate_session(session)
    session
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  SHOPIFY_DOMAIN = Rails.application.secrets.shopify_domain
  protect_from_forgery with: :null_session
end

app/controllers/authenticated_controller.rb
# frozen_string_literal: true

class AuthenticatedController < ApplicationController
  include ShopifyApp::Authenticated
end

app/controllers/graphql_controller.rb
# frozen_string_literal: true

class GraphqlController < ApplicationController
  before_action :connect_to_store, only: [:execute]

  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # current_user: current_user,
    }
    result = CoffeeShopSchema.execute(
      query,
      variables:      variables,
      context:        context,
      operation_name: operation_name
    )
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?

    handle_error_in_development e
  end

  private

  def connect_to_store
    Shop.first.connect_to_store
  end

  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def handle_error_in_development(error)
    logger.error error.message
    logger.error error.backtrace.join("\n")

    render json: {error: {message: error.message, backtrace: error.backtrace}, data: {}}, status: :internal_server_error
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < AuthenticatedController
  def index
    @products = ShopifyAPI::Product.find(:all)
  end

  def new
    @product = ShopifyAPI::Product.new(set_empty_attributes)
  end

  def create
    @product = Products::Create.call(permit_params)
    render :show
  end

  def show
    @product = ShopifyAPI::Product.find(params[:id])
  end

  def edit
    @product = ShopifyAPI::Product.find(params[:id])
  end

  def update
    @product = Products::Update.call(permit_params)
    render :show
  end

  def destroy
    ShopifyAPI::Product.find(params[:id]).destroy
  end

  private

  def set_empty_attributes
    {
      title:        "",
      body_html:    "",
      product_type: "PRODUCT",
      variants:     [
        {
          price:  "",
          weight: ""
        }
      ],
      metafields:   [
        {
          value: ""
        }
      ]
    }
  end

  def permit_params
    params
      .permit(
        :id,
        shopify_api_product: %i[title body_html product_type],
        variants:            %i[weight price],
        metafields:          [:value]
      )
      .merge(vendor: "nixshoptest")
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
  def image_url(product)
    product.image.nil? ? default_image_path : product.image.attributes["src"]
  end

  def default_image_path
    "https://shop.tastycoffee.ru/files/shares/data/_newpack5/espresso-mono/brazil-cerrado-025.png"
  end

  def form_product_url(product:)
    case controller.action_name
    when "new"
      products_path
    when "edit"
      product_path(product)
    end
  end
end

app/views/layouts/_flash_messages.html.haml
- content_for :javascript do
  = content_tag(:div, nil, id: 'shopify-app-flash', data: { flash: { notice: flash[:notice], error: flash[:error] } })

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  = link_to "Admin", :root, class: "navbar-brand"
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        %a.nav-link{:href => "#"}
          Home
          %span.sr-only (current)
      %li.nav-item
        = link_to "Create Product", new_product_path, class: "nav-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CoffeeShop
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %header
      .container
        = render "layouts/nav"
        %br/
        = yield

app/views/layouts/embedded_app.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    - application_name = ShopifyApp.configuration.application_name
    %title= application_name
    = stylesheet_link_tag 'application'
    - if ShopifyApp.use_webpacker?
      = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    - else
      = javascript_include_tag 'application', "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .app-wrapper
      .app-content
        %main{:role => "main"}
          = yield
    = render 'layouts/flash_messages'
    %script{:src => "https://cdn.shopify.com/s/assets/external/app.js?#{Time.now.strftime('%Y%m%d%H')}"}
    = content_tag(:div, nil, id: 'shopify-app-init', data: {              |
        api_key: ShopifyApp.configuration.api_key,                        |
        shop_origin: ("https://#{ @shop_session.url }" if @shop_session), |
        debug: Rails.env.development?                                     |
      } )                                                                 |
    - if content_for?(:javascript)
      #ContentForJavascript{"data-turbolinks-temporary" => ""}
        = yield :javascript

app/views/products/_form.html.haml
= form_for product, url: form_product_url(product: product), method: method do |form|

  .form-group.row
    .col-3.col-form-label
      = form.label :title
    .col-9
      = form.text_field :title, class: "form-control"

  .form-group.row
    .col-3.col-form-label
      = form.label :body_html
    .col-9
      = form.cktext_area :body_html, class: "form-control"

  .form-group.row
    .col-3.col-form-label
      = form.label :image
    .col-9
      = form.file_field :image

  = fields_for :variants, product.variants[0] do |variant|
    .form-group.row
      .col-3.col-form-label
        = variant.label :weight

      .col-9
        .input-group
          = variant.text_field :weight, class: "form-control"
          .input-group-append
            .input-group-text kg

    .form-group.row
      .col-3.col-form-label
        = variant.label :price
      .col-9
        .input-group
          = variant.text_field :price, class: "form-control"
          .input-group-append
            .input-group-text $


  = fields_for :metafields, product.metafields[0] do |meta|
    .form-group.row
      .col-3.col-form-label
        = meta.label :position
      .col-9
        .input-group
          = meta.text_field :value, class: "form-control"
          .input-group-append
            .input-group-text
              %i.fa.fa-area-chart

      :css
        #map { height: 400px; width: 100%; }
      #map
      :javascript
        mapboxgl.accessToken = 'pk.eyJ1Ijoic29tMmgiLCJhIjoiY2s3d2FsejlpMDA3czNmcXJ3YzZrdG04aCJ9.BbPf2gG-DvC9ho8tH-X7bw';
        var map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v11',
            center: [0, 0],
            zoom: 2
        });

        var canvas = map.getCanvasContainer();

        var geojson = {
          'type': 'FeatureCollection',
          'features': [{
              'type': 'Feature',
              'geometry': {
                  'type': 'Point',
                  'coordinates': [0, 0]
              }
          }]
        };

        function onMove(e) {
          var coords = e.lngLat;
          canvas.style.cursor = 'grabbing';
          geojson.features[0].geometry.coordinates =  [coords.lng, coords.lat];
          map.getSource('point').setData(geojson);
        }

        function onUp(e) {
          var coords = e.lngLat;
            document.getElementById('metafields_value').value =  [coords.lng, coords.lat].join();
            canvas.style.cursor = '';
            map.off('mousemove', onMove);
            map.off('touchmove', onMove);
        }

        map.on('load', function() {
            map.addSource('point', {
                'type': 'geojson',
                'data': geojson
            });

            map.addLayer({
                'id': 'point',
                'type': 'circle',
                'source': 'point',
                'paint': {
                    'circle-radius': 10,
                    'circle-color': '#3887be'
                }
            });

            map.on('mouseenter', 'point', function() {
                map.setPaintProperty('point', 'circle-color', '#3bb2d0');
                canvas.style.cursor = 'move';
            });

            map.on('mouseleave', 'point', function() {
                map.setPaintProperty('point', 'circle-color', '#3887be');
                canvas.style.cursor = '';
            });

            map.on('mousedown', 'point', function(e) {
                e.preventDefault();
                canvas.style.cursor = 'grab';
                map.on('mousemove', onMove);
                map.once('mouseup', onUp);
            });

            map.on('touchstart', 'point', function(e) {
                if (e.points.length !== 1) return;
                e.preventDefault();
                map.on('touchmove', onMove);
                map.once('touchend', onUp);
            });
        });

  .form-group.row
    .offset-3.col-9
      = form.submit class: "btn btn-primary"

app/views/products/edit.html.haml
= render "form", product: @product, method: :put

app/views/products/index.html.haml
%h2 Products
%br/

%table.table.table-striped.table-bordered
  %thead
    %tr
      %th{:scope => "col"}
      %th{:scope => "col"} Name
      %th{:scope => "col"} Price
      %th{:scope => "col"} Weight
      %th{:scope => "col"} Action

  %tbody
    - @products.each do |product|
      :ruby
        img_src = image_url(product)
      %tr
        %td
          %img.rounded.img-fluid{:alt => "Default", :height => "256", :width => "189", :src => img_src}
        %td= link_to product.title, product_path(product.attributes["id"])
        %td= product.variants[0].price
        %td= product.variants[0].weight
        %td= link_to "Edit", edit_product_path(product.attributes["id"])

app/views/products/new.html.haml
= render "form", product: @product, method: :post

app/views/products/show.html.haml
:ruby
  img_src = image_url(@product)

.container
  %h2 Product #{@product.title}
  %br/
  .jumbotron
    .row
      .col-8
        %img.rounded.img-fluid{:alt => "Default", :src => img_src}/
        %br/
        %br/
      .col-4
        %table.table.table-bordered.table-striped
          %tr
            %td Id
            %td= @product.id
          %tr
            %td Title
            %td= @product.title
          %tr
            %td Vendor
            %td= @product.vendor
          %tr
            %td Product type
            %td= @product.product_type
          %tr
            %td Created at
            %td= @product.created_at
          %tr
            %td Updated at
            %td= @product.updated_at
          %tr
            %td Published at
            %td= @product.published_at
          %tr
            %td Handle
            %td= @product.handle
          %tr
            %td Published scope
            %td= @product.published_scope
          %tr
            %td Price
            %td= @product.variants.first.price
          %tr
            %td Position
            %td= @product.metafields[0]&.value


      = raw(@product.body_html)